# -*- coding: utf-8 -*-
"""stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Rb_0QKXILFm7AXa8QiBdkPWBrZQIAlI

**Z-Distribution**
"""

from scipy import stats as st

Z0=float(input("Enter the input value for unit distribution: "))
print(st.norm.cdf(Z0))

alpha=float(input("Enter the Score value for unit distribution: "))
print(st.norm.ppf(alpha))

"""**Chi-square Distribution**"""

y0=float(input("Enter the input value for chisquare distribution: "))
dof=int(input("Enter degree of freedom: "))
chipro=st.chi2.cdf(y0,dof)
print(f"Chisquare probability for {y0} is: {chipro}")

alpha=float(input("Enter the Score value for chisquare distribution: "))
dof=int(input("Enter degree of freedom: "))
y0=st.chi2.ppf(alpha,dof) 
print(f"Value of y0 for which chisquare probability is equal to {alpha}: {Z0}")

"""**T-Distribution**"""

t0=float(input("Enter input value for T-distribution: "))
dof=int(input("Enter degree of freedom: "))
tprob=st.t.cdf(t0,dof)
print(f"probability of T<=T0 is: {tprob}")

alpha=float(input("Enter T-score for T-distribution: "))
dof=int(input("Enter degree of freedom: "))
t0=st.t.ppf(alpha,dof)
print(t0)

"""**F-Distribution**"""

F0=float(input("Enter value for F-distribution: "))
dof1=int(input("Enter degree of freedom v1: "))
dof2=int(input("Enter degree of freedom v2: "))
fprob=st.f.cdf(F0,dof1,dof2)
print(f"probability of F<=F0 is: {fprob}")

alpha=float(input("Enter f-score: "))
dof1=int(input("Enter degree of freedom v1: "))
dof2=int(input("Enter degree of freedom v2: "))
z0=st.f.cdf(alpha,dof1,dof2)
print(f"probability of F<=F0 is: {F0}")